name: SSH to Server and Execute Scripts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.YOUR_SECRET_KEY }}" > githubAction.pem
        chmod 600 githubAction.pem

    - name: SSH into server and execute scripts
      run: |
        ssh -i githubAction.pem ubuntu@ec2-54-252-24-102.ap-southeast-2.compute.amazonaws.com 'bash -s' << 'ENDSSH'
        # Commands to run on the remote server
        cd COMP30022-IT-Project
        git pull
        sudo systemctl restart myflaskapp
        # Add more commands here if needed
        ENDSSH
