name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Execute SSH command
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_SSH_ADDRESS }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd COMP30022-IT-Project
          git pull
          sudo systemctl restart myflaskapp
